drop table country if exists;

create table country (
  id integer,
  countryname varchar(32),
  countrycode varchar(2)
);

insert into country (id, countryname, countrycode) values(1,'Angola','AO');
insert into country (id, countryname, countrycode) values(2,'Afghanistan','AF');
insert into country (id, countryname, countrycode) values(3,'Albania','AL');
insert into country (id, countryname, countrycode) values(4,'Algeria','DZ');
insert into country (id, countryname, countrycode) values(5,'Andorra','AD');
insert into country (id, countryname, countrycode) values(6,'Anguilla','AI');
insert into country (id, countryname, countrycode) values(7,'Antigua and Barbuda','AG');
insert into country (id, countryname, countrycode) values(8,'Argentina','AR');
insert into country (id, countryname, countrycode) values(9,'Armenia','AM');
insert into country (id, countryname, countrycode) values(10,'Australia','AU');
insert into country (id, countryname, countrycode) values(11,'Austria','AT');
insert into country (id, countryname, countrycode) values(12,'Azerbaijan','AZ');
insert into country (id, countryname, countrycode) values(13,'Bahamas','BS');
insert into country (id, countryname, countrycode) values(14,'Bahrain','BH');
insert into country (id, countryname, countrycode) values(15,'Bangladesh','BD');
insert into country (id, countryname, countrycode) values(16,'Barbados','BB');
insert into country (id, countryname, countrycode) values(17,'Belarus','BY');
insert into country (id, countryname, countrycode) values(18,'Belgium','BE');
insert into country (id, countryname, countrycode) values(19,'Belize','BZ');
insert into country (id, countryname, countrycode) values(20,'Benin','BJ');
insert into country (id, countryname, countrycode) values(21,'Bermuda Is.','BM');
insert into country (id, countryname, countrycode) values(22,'Bolivia','BO');
insert into country (id, countryname, countrycode) values(23,'Botswana','BW');
insert into country (id, countryname, countrycode) values(24,'Brazil','BR');
insert into country (id, countryname, countrycode) values(25,'Brunei','BN');
insert into country (id, countryname, countrycode) values(26,'Bulgaria','BG');
insert into country (id, countryname, countrycode) values(27,'Burkina-faso','BF');
insert into country (id, countryname, countrycode) values(28,'Burma','MM');
insert into country (id, countryname, countrycode) values(29,'Burundi','BI');
insert into country (id, countryname, countrycode) values(30,'Cameroon','CM');
insert into country (id, countryname, countrycode) values(31,'Canada','CA');
insert into country (id, countryname, countrycode) values(32,'Central African Republic','CF');
insert into country (id, countryname, countrycode) values(33,'Chad','TD');
insert into country (id, countryname, countrycode) values(34,'Chile','CL');
insert into country (id, countryname, countrycode) values(35,'China','CN');
insert into country (id, countryname, countrycode) values(36,'Colombia','CO');
insert into country (id, countryname, countrycode) values(37,'Congo','CG');
insert into country (id, countryname, countrycode) values(38,'Cook Is.','CK');
insert into country (id, countryname, countrycode) values(39,'Costa Rica','CR');
insert into country (id, countryname, countrycode) values(40,'Cuba','CU');
insert into country (id, countryname, countrycode) values(41,'Cyprus','CY');
insert into country (id, countryname, countrycode) values(42,'Czech Republic','CZ');
insert into country (id, countryname, countrycode) values(43,'Denmark','DK');
insert into country (id, countryname, countrycode) values(44,'Djibouti','DJ');
insert into country (id, countryname, countrycode) values(45,'Dominica Rep.','DO');
insert into country (id, countryname, countrycode) values(46,'Ecuador','EC');
insert into country (id, countryname, countrycode) values(47,'Egypt','EG');
insert into country (id, countryname, countrycode) values(48,'EI Salvador','SV');
insert into country (id, countryname, countrycode) values(49,'Estonia','EE');
insert into country (id, countryname, countrycode) values(50,'Ethiopia','ET');
insert into country (id, countryname, countrycode) values(51,'Fiji','FJ');
insert into country (id, countryname, countrycode) values(52,'Finland','FI');
insert into country (id, countryname, countrycode) values(53,'France','FR');
insert into country (id, countryname, countrycode) values(54,'French Guiana','GF');
insert into country (id, countryname, countrycode) values(55,'Gabon','GA');
insert into country (id, countryname, countrycode) values(56,'Gambia','GM');
insert into country (id, countryname, countrycode) values(57,'Georgia','GE');
insert into country (id, countryname, countrycode) values(58,'Germany','DE');
insert into country (id, countryname, countrycode) values(59,'Ghana','GH');
insert into country (id, countryname, countrycode) values(60,'Gibraltar','GI');
insert into country (id, countryname, countrycode) values(61,'Greece','GR');
insert into country (id, countryname, countrycode) values(62,'Grenada','GD');
insert into country (id, countryname, countrycode) values(63,'Guam','GU');
insert into country (id, countryname, countrycode) values(64,'Guatemala','GT');
insert into country (id, countryname, countrycode) values(65,'Guinea','GN');
insert into country (id, countryname, countrycode) values(66,'Guyana','GY');
insert into country (id, countryname, countrycode) values(67,'Haiti','HT');
insert into country (id, countryname, countrycode) values(68,'Honduras','HN');
insert into country (id, countryname, countrycode) values(69,'Hongkong','HK');
insert into country (id, countryname, countrycode) values(70,'Hungary','HU');
insert into country (id, countryname, countrycode) values(71,'Iceland','IS');
insert into country (id, countryname, countrycode) values(72,'India','IN');
insert into country (id, countryname, countrycode) values(73,'Indonesia','ID');
insert into country (id, countryname, countrycode) values(74,'Iran','IR');
insert into country (id, countryname, countrycode) values(75,'Iraq','IQ');
insert into country (id, countryname, countrycode) values(76,'Ireland','IE');
insert into country (id, countryname, countrycode) values(77,'Israel','IL');
insert into country (id, countryname, countrycode) values(78,'Italy','IT');
insert into country (id, countryname, countrycode) values(79,'Jamaica','JM');
insert into country (id, countryname, countrycode) values(80,'Japan','JP');
insert into country (id, countryname, countrycode) values(81,'Jordan','JO');
insert into country (id, countryname, countrycode) values(82,'Kampuchea (Cambodia )','KH');
insert into country (id, countryname, countrycode) values(83,'Kazakstan','KZ');
insert into country (id, countryname, countrycode) values(84,'Kenya','KE');
insert into country (id, countryname, countrycode) values(85,'Korea','KR');
insert into country (id, countryname, countrycode) values(86,'Kuwait','KW');
insert into country (id, countryname, countrycode) values(87,'Kyrgyzstan','KG');
insert into country (id, countryname, countrycode) values(88,'Laos','LA');
insert into country (id, countryname, countrycode) values(89,'Latvia','LV');
insert into country (id, countryname, countrycode) values(90,'Lebanon','LB');
insert into country (id, countryname, countrycode) values(91,'Lesotho','LS');
insert into country (id, countryname, countrycode) values(92,'Liberia','LR');
insert into country (id, countryname, countrycode) values(93,'Libya','LY');
insert into country (id, countryname, countrycode) values(94,'Liechtenstein','LI');
insert into country (id, countryname, countrycode) values(95,'Lithuania','LT');
insert into country (id, countryname, countrycode) values(96,'Luxembourg','LU');
insert into country (id, countryname, countrycode) values(97,'Macao','MO');
insert into country (id, countryname, countrycode) values(98,'Madagascar','MG');
insert into country (id, countryname, countrycode) values(99,'Malawi','MW');
insert into country (id, countryname, countrycode) values(100,'Malaysia','MY');
insert into country (id, countryname, countrycode) values(101,'Maldives','MV');
insert into country (id, countryname, countrycode) values(102,'Mali','ML');
insert into country (id, countryname, countrycode) values(103,'Malta','MT');
insert into country (id, countryname, countrycode) values(104,'Mauritius','MU');
insert into country (id, countryname, countrycode) values(105,'Mexico','MX');
insert into country (id, countryname, countrycode) values(106,'Moldova, Republic of','MD');
insert into country (id, countryname, countrycode) values(107,'Monaco','MC');
insert into country (id, countryname, countrycode) values(108,'Mongolia','MN');
insert into country (id, countryname, countrycode) values(109,'Montserrat Is','MS');
insert into country (id, countryname, countrycode) values(110,'Morocco','MA');
insert into country (id, countryname, countrycode) values(111,'Mozambique','MZ');
insert into country (id, countryname, countrycode) values(112,'Namibia','NA');
insert into country (id, countryname, countrycode) values(113,'Nauru','NR');
insert into country (id, countryname, countrycode) values(114,'Nepal','NP');
insert into country (id, countryname, countrycode) values(115,'Netherlands','NL');
insert into country (id, countryname, countrycode) values(116,'New Zealand','NZ');
insert into country (id, countryname, countrycode) values(117,'Nicaragua','NI');
insert into country (id, countryname, countrycode) values(118,'Niger','NE');
insert into country (id, countryname, countrycode) values(119,'Nigeria','NG');
insert into country (id, countryname, countrycode) values(120,'North Korea','KP');
insert into country (id, countryname, countrycode) values(121,'Norway','NO');
insert into country (id, countryname, countrycode) values(122,'Oman','OM');
insert into country (id, countryname, countrycode) values(123,'Pakistan','PK');
insert into country (id, countryname, countrycode) values(124,'Panama','PA');
insert into country (id, countryname, countrycode) values(125,'Papua New Cuinea','PG');
insert into country (id, countryname, countrycode) values(126,'Paraguay','PY');
insert into country (id, countryname, countrycode) values(127,'Peru','PE');
insert into country (id, countryname, countrycode) values(128,'Philippines','PH');
insert into country (id, countryname, countrycode) values(129,'Poland','PL');
insert into country (id, countryname, countrycode) values(130,'French Polynesia','PF');
insert into country (id, countryname, countrycode) values(131,'Portugal','PT');
insert into country (id, countryname, countrycode) values(132,'Puerto Rico','PR');
insert into country (id, countryname, countrycode) values(133,'Qatar','QA');
insert into country (id, countryname, countrycode) values(134,'Romania','RO');
insert into country (id, countryname, countrycode) values(135,'Russia','RU');
insert into country (id, countryname, countrycode) values(136,'Saint Lueia','LC');
insert into country (id, countryname, countrycode) values(137,'Saint Vincent','VC');
insert into country (id, countryname, countrycode) values(138,'San Marino','SM');
insert into country (id, countryname, countrycode) values(139,'Sao Tome and Principe','ST');
insert into country (id, countryname, countrycode) values(140,'Saudi Arabia','SA');
insert into country (id, countryname, countrycode) values(141,'Senegal','SN');
insert into country (id, countryname, countrycode) values(142,'Seychelles','SC');
insert into country (id, countryname, countrycode) values(143,'Sierra Leone','SL');
insert into country (id, countryname, countrycode) values(144,'Singapore','SG');
insert into country (id, countryname, countrycode) values(145,'Slovakia','SK');
insert into country (id, countryname, countrycode) values(146,'Slovenia','SI');
insert into country (id, countryname, countrycode) values(147,'Solomon Is','SB');
insert into country (id, countryname, countrycode) values(148,'Somali','SO');
insert into country (id, countryname, countrycode) values(149,'South Africa','ZA');
insert into country (id, countryname, countrycode) values(150,'Spain','ES');
insert into country (id, countryname, countrycode) values(151,'Sri Lanka','LK');
insert into country (id, countryname, countrycode) values(152,'St.Lucia','LC');
insert into country (id, countryname, countrycode) values(153,'St.Vincent','VC');
insert into country (id, countryname, countrycode) values(154,'Sudan','SD');
insert into country (id, countryname, countrycode) values(155,'Suriname','SR');
insert into country (id, countryname, countrycode) values(156,'Swaziland','SZ');
insert into country (id, countryname, countrycode) values(157,'Sweden','SE');
insert into country (id, countryname, countrycode) values(158,'Switzerland','CH');
insert into country (id, countryname, countrycode) values(159,'Syria','SY');
insert into country (id, countryname, countrycode) values(160,'Taiwan','TW');
insert into country (id, countryname, countrycode) values(161,'Tajikstan','TJ');
insert into country (id, countryname, countrycode) values(162,'Tanzania','TZ');
insert into country (id, countryname, countrycode) values(163,'Thailand','TH');
insert into country (id, countryname, countrycode) values(164,'Togo','TG');
insert into country (id, countryname, countrycode) values(165,'Tonga','TO');
insert into country (id, countryname, countrycode) values(166,'Trinidad and Tobago','TT');
insert into country (id, countryname, countrycode) values(167,'Tunisia','TN');
insert into country (id, countryname, countrycode) values(168,'Turkey','TR');
insert into country (id, countryname, countrycode) values(169,'Turkmenistan','TM');
insert into country (id, countryname, countrycode) values(170,'Uganda','UG');
insert into country (id, countryname, countrycode) values(171,'Ukraine','UA');
insert into country (id, countryname, countrycode) values(172,'United Arab Emirates','AE');
insert into country (id, countryname, countrycode) values(173,'United Kiongdom','GB');
insert into country (id, countryname, countrycode) values(174,'United States of America','US');
insert into country (id, countryname, countrycode) values(175,'Uruguay','UY');
insert into country (id, countryname, countrycode) values(176,'Uzbekistan','UZ');
insert into country (id, countryname, countrycode) values(177,'Venezuela','VE');
insert into country (id, countryname, countrycode) values(178,'Vietnam','VN');
insert into country (id, countryname, countrycode) values(179,'Yemen','YE');
insert into country (id, countryname, countrycode) values(180,'Yugoslavia','YU');
insert into country (id, countryname, countrycode) values(181,'Zimbabwe','ZW');
insert into country (id, countryname, countrycode) values(182,'Zaire','ZR');
insert into country (id, countryname, countrycode) values(183,'Zambia','ZM');

drop table user if exists;

create table user (
                      id integer,
                      name varchar(32),
                      py varchar(5)
);

insert into user(id, name, py) values('1','毕淑儒','BSR');
insert into user(id, name, py) values('2','蔡兴熙','CXX');
insert into user(id, name, py) values('3','曾三杰','ZSJ');
insert into user(id, name, py) values('4','常元琴','CYQ');
insert into user(id, name, py) values('5','陈栋芬','CDF');
insert into user(id, name, py) values('6','陈宁婷','CNZ');
insert into user(id, name, py) values('7','陈瑞','CR');
insert into user(id, name, py) values('8','陈武宵','CWX');
insert into user(id, name, py) values('9','陈晓丽','CXL');
insert into user(id, name, py) values('10','陈翼涛','CYT');
insert into user(id, name, py) values('11','陈宇然','CYR');
insert into user(id, name, py) values('12','陈震','CZ');
insert into user(id, name, py) values('13','程太君','CTJ');
insert into user(id, name, py) values('14','程玉娜','CYN');
insert into user(id, name, py) values('15','丛贺轩','CHX');
insert into user(id, name, py) values('16','戴国宇','DGY');
insert into user(id, name, py) values('17','戴杰亮','DJL');
insert into user(id, name, py) values('18','丁玉华','DYH');
insert into user(id, name, py) values('19','董秋明','DQM');
insert into user(id, name, py) values('20','董政厚','DZH');
insert into user(id, name, py) values('21','杜玉焱','DYZ');
insert into user(id, name, py) values('22','段瑜芝','DZZ');
insert into user(id, name, py) values('23','傅广友','FGY');
insert into user(id, name, py) values('24','傅井飞','FJF');
insert into user(id, name, py) values('25','高辉涛','GHT');
insert into user(id, name, py) values('26','高龙飞','GLF');
insert into user(id, name, py) values('27','高汝英','GRY');
insert into user(id, name, py) values('28','高云天','GYT');
insert into user(id, name, py) values('29','郭义民','GYM');
insert into user(id, name, py) values('30','郭永洪','GYH');
insert into user(id, name, py) values('31','韩国茜','HGZ');
insert into user(id, name, py) values('32','韩龙康','HLK');
insert into user(id, name, py) values('33','韩伟佳','HWJ');
insert into user(id, name, py) values('34','韩扬谦','HYQ');
insert into user(id, name, py) values('35','郝静生','HJS');
insert into user(id, name, py) values('36','何柏红','HBH');
insert into user(id, name, py) values('37','何彩智','HCZ');
insert into user(id, name, py) values('38','何陶增','HTZ');
insert into user(id, name, py) values('39','何薇','HZ');
insert into user(id, name, py) values('40','何小凡','HXF');
insert into user(id, name, py) values('41','何振平','HZP');
insert into user(id, name, py) values('42','洪彩辉','HCH');
insert into user(id, name, py) values('43','胡仕明','HSM');
insert into user(id, name, py) values('44','黄建朋','HJP');
insert into user(id, name, py) values('45','黄祥荣','HXR');
insert into user(id, name, py) values('46','黄璇平','HZP');
insert into user(id, name, py) values('47','贾茂飞','JMF');
insert into user(id, name, py) values('48','李迪茹','LDR');
insert into user(id, name, py) values('49','李桂博','LGB');
insert into user(id, name, py) values('50','李国祯','LGZ');
insert into user(id, name, py) values('51','李宏川','LHC');
insert into user(id, name, py) values('52','李梅','LM');
insert into user(id, name, py) values('53','李媚文','LMW');
insert into user(id, name, py) values('54','李孟惠','LMH');
insert into user(id, name, py) values('55','李南懋','LNZ');
insert into user(id, name, py) values('56','李鹏龙','LPL');
insert into user(id, name, py) values('57','李诗庸','LSY');
insert into user(id, name, py) values('58','李姝勇','LZY');
insert into user(id, name, py) values('59','李树鹏','LSP');
insert into user(id, name, py) values('60','李薇红','LZH');
insert into user(id, name, py) values('61','李文章','LWZ');
insert into user(id, name, py) values('62','李星佳','LXJ');
insert into user(id, name, py) values('63','李兴','LX');
insert into user(id, name, py) values('64','李秀倩','LXZ');
insert into user(id, name, py) values('65','李艳生','LYS');
insert into user(id, name, py) values('66','李燕金','LYJ');
insert into user(id, name, py) values('67','李玉彪','LYB');
insert into user(id, name, py) values('68','李振峰','LZF');
insert into user(id, name, py) values('69','梁斌芳','LBF');
insert into user(id, name, py) values('70','梁国云','LGY');
insert into user(id, name, py) values('71','梁巧爱','LQA');
insert into user(id, name, py) values('72','梁照金','LZJ');
insert into user(id, name, py) values('73','林婧美','LZM');
insert into user(id, name, py) values('74','林沛寿','LPS');
insert into user(id, name, py) values('75','林薇程','LZC');
insert into user(id, name, py) values('76','林伟玉','LWY');
insert into user(id, name, py) values('77','林艺玲','LYL');
insert into user(id, name, py) values('78','刘睿','LR');
insert into user(id, name, py) values('79','刘芊芊','LQQ');
insert into user(id, name, py) values('80','刘海波','LHB');
insert into user(id, name, py) values('81','刘斓琴','LZQ');
insert into user(id, name, py) values('82','刘磊东','LLD');
insert into user(id, name, py) values('83','刘明琪','LMZ');
insert into user(id, name, py) values('84','刘铭恩','LME');
insert into user(id, name, py) values('85','刘任恺','LRZ');
insert into user(id, name, py) values('86','刘水秋','LSQ');
insert into user(id, name, py) values('87','刘文萱','LWZ');
insert into user(id, name, py) values('88','刘祥瑶','LXY');
insert into user(id, name, py) values('89','刘薪坪','LXP');
insert into user(id, name, py) values('90','刘秀涛','LXT');
insert into user(id, name, py) values('91','刘彦利','LYL');
insert into user(id, name, py) values('92','刘益存','LYC');
insert into user(id, name, py) values('93','龙子苹','LZP');
insert into user(id, name, py) values('94','卢秀剑','LXJ');
insert into user(id, name, py) values('95','罗乔华','LQH');
insert into user(id, name, py) values('96','罗希清','LXQ');
insert into user(id, name, py) values('97','马家兰','MJL');
insert into user(id, name, py) values('98','马莲莹','MLY');
insert into user(id, name, py) values('99','马宁文','MNW');
insert into user(id, name, py) values('100','马水鹏','MSP');
insert into user(id, name, py) values('101','孟三云','MSY');
insert into user(id, name, py) values('102','孟寿云','MSY');
insert into user(id, name, py) values('103','聂伟元','NWY');
insert into user(id, name, py) values('104','潘永飞','PYF');
insert into user(id, name, py) values('105','彭健颖','PJY');
insert into user(id, name, py) values('106','钱文松','QWS');
insert into user(id, name, py) values('107','屈江珍','QJZ');
insert into user(id, name, py) values('108','邵建林','SJL');
insert into user(id, name, py) values('109','施家晖','SJZ');
insert into user(id, name, py) values('110','施艺英','SYY');
insert into user(id, name, py) values('111','孙常程','SCC');
insert into user(id, name, py) values('112','谭佳盈','TJY');
insert into user(id, name, py) values('113','唐春珊','TCS');
insert into user(id, name, py) values('114','唐军霞','TJX');
insert into user(id, name, py) values('115','唐里丽','TLL');
insert into user(id, name, py) values('116','陶姐华','TJH');
insert into user(id, name, py) values('117','万圻艳','WZY');
insert into user(id, name, py) values('118','王傲凤','WAF');
insert into user(id, name, py) values('119','王德英','WDY');
insert into user(id, name, py) values('120','王鼎华','WDH');
insert into user(id, name, py) values('121','王慧','WH');
insert into user(id, name, py) values('122','王佳光','WJG');
insert into user(id, name, py) values('123','王家胜','WJS');
insert into user(id, name, py) values('124','王竞飞','WJF');
insert into user(id, name, py) values('125','王科磊','WKL');
insert into user(id, name, py) values('126','王丽章','WLZ');
insert into user(id, name, py) values('127','王励苗','WLM');
insert into user(id, name, py) values('128','王美东','WMD');
insert into user(id, name, py) values('129','王美媛','WMZ');
insert into user(id, name, py) values('130','王蕊颖','WRY');
insert into user(id, name, py) values('131','王士成','WSC');
insert into user(id, name, py) values('132','王熙斌','WXB');
insert into user(id, name, py) values('133','王香军','WXJ');
insert into user(id, name, py) values('134','王休娜','WXN');
insert into user(id, name, py) values('135','王仪行','WYX');
insert into user(id, name, py) values('136','王赢基','WYJ');
insert into user(id, name, py) values('137','王云芯','WYX');
insert into user(id, name, py) values('138','王郑林','WZL');
insert into user(id, name, py) values('139','王治良','WZL');
insert into user(id, name, py) values('140','王忠宇','WZY');
insert into user(id, name, py) values('141','王子冰','WZB');
insert into user(id, name, py) values('142','韦新裕','WXY');
insert into user(id, name, py) values('143','魏复冉','WFR');
insert into user(id, name, py) values('144','吴翰志','WHZ');
insert into user(id, name, py) values('145','吴美森','WMS');
insert into user(id, name, py) values('146','吴翔良','WXL');
insert into user(id, name, py) values('147','吴艳伟','WYW');
insert into user(id, name, py) values('148','吴钲辉','WZH');
insert into user(id, name, py) values('149','向盼洛','XPL');
insert into user(id, name, py) values('150','萧恩','XE');
insert into user(id, name, py) values('151','萧军杰','XJJ');
insert into user(id, name, py) values('152','萧圣梅','XSM');
insert into user(id, name, py) values('153','谢辰吉','XCJ');
insert into user(id, name, py) values('154','徐郎求','XLQ');
insert into user(id, name, py) values('155','徐铭森','XMS');
insert into user(id, name, py) values('156','徐蓉伟','XRW');
insert into user(id, name, py) values('157','许为梧','XWW');
insert into user(id, name, py) values('158','阎皓河','YZH');
insert into user(id, name, py) values('159','阎思华','YSH');
insert into user(id, name, py) values('160','杨爱秀','YAX');
insert into user(id, name, py) values('161','杨昆飞','YKF');
insert into user(id, name, py) values('162','杨良林','YLL');
insert into user(id, name, py) values('163','杨少君','YSJ');
insert into user(id, name, py) values('164','杨玉丽','YYL');
insert into user(id, name, py) values('165','杨之安','YZA');
insert into user(id, name, py) values('166','尤榕锋','YZF');
insert into user(id, name, py) values('167','余俊珠','YJZ');
insert into user(id, name, py) values('168','袁江蔓','YJM');
insert into user(id, name, py) values('169','张必翰','ZBH');
insert into user(id, name, py) values('170','张昌颜','ZCY');
insert into user(id, name, py) values('171','张恩星','ZEX');
insert into user(id, name, py) values('172','张飞强','ZFQ');
insert into user(id, name, py) values('173','张凤焯','ZFZ');
insert into user(id, name, py) values('174','张国强','ZGQ');
insert into user(id, name, py) values('175','张计欣','ZJX');
insert into user(id, name, py) values('176','张家颖','ZJY');
insert into user(id, name, py) values('177','张金安','ZJA');
insert into user(id, name, py) values('178','张莉','ZL');
insert into user(id, name, py) values('179','张米龙','ZML');
insert into user(id, name, py) values('180','张善渊','ZSY');
insert into user(id, name, py) values('181','张万敏','ZWM');
insert into user(id, name, py) values('182','张晓林','ZXL');
insert into user(id, name, py) values('183','张秀高','ZXG');